### ISSUE TITLE
🤔 [QUESTION]绘制多边形时，控制台大量打印“请使用 lngLatToPixel 方法替代。”

### ISSUE THREAD

**Issue by cabfan** [antvis/L7Draw#100]
### 🐛 Question description [Please make everyone to understand it]
使用polygon进行绘制时，查看控制台，输出了大量的提示信息 “请使用 lngLatToPixel 方法替代。”

### 🏞 Expected result

期望更新为推荐的方法

**Comment by halleystar** [comment]
确实打印了大量的 提示信息，开发者竟然不处理这个问题？

**Comment by heiyexing** [comment]
检查后是由 L7 Scene 的 lngLatToPixel 方法导致，可以跳转至 [L7 issues](https://github.com/antvis/L7/issue) 提 Issue
