### ISSUE TITLE
有没有办法修改线条的properties？

### ISSUE THREAD

**Issue by oyal** [antvis/L7Draw#107]
可否对线的properties进行操作？我想对每根线的颜色宽度进行设置，如：

<https://geojson.io>

[![zZ3HfI.png](https://s1.ax1x.com/2022/11/16/zZ3HfI.png)](https://imgse.com/i/zZ3HfI)

**Comment by heiyexing** [comment]
每根线指的是不同的LineString  Feature   还是同一个 Feature 两两点之间的线段颜色

**Comment by oyal** [comment]
> 每根线指的是不同的LineString Feature 还是同一个 Feature 两两点之间的线段颜色

感谢回复！有没有办法对每个线段的颜色进行设置？

目前我的想法是，能否往 line 或者 nodes 里的 `properties` 加入一些参数，然后通过 callback 来设置样式。（在官网示例 [定制公交场景](https://l7draw.antv.vision/example/usage/bus) 看到可以通过修改 style 里的 callback 来修改线条样式）

看了 L7 的官网只有一个 [updateFeaturePropertiesById](https://l7.antv.antgroup.com/api/source/source#updatefeaturepropertiesbyid) 可以对线条的 `properties` 做修改，但是和 `L7Draw` 结合起来也有点困难。不知道我方向是不是错的？

我目前是想做到下面这种效果，可以根据数据来改变颜色

期盼您的回复

[![zYwtZq.jpg](https://s1.ax1x.com/2022/11/25/zYwtZq.jpg)](https://imgse.com/i/zYwtZq)

**Comment by heiyexing** [comment]
如果你使用 DrawLine 是基于已有的线路数据基础之上，对已有线路进行编辑的话，可以对传入的线路初始值中，设置你自己的业务字段，L7Draw 是会对初始数据中的字段做保留的，之后就可以用你说的 callback 做线路颜色的值映射就行了
![image](https://user-images.githubusercontent.com/29321750/204206344-39b4ff9f-8e6e-4e5c-978c-d0b0807bc834.png)
