### ISSUE TITLE
🐛 [BUG] DrawPoint 图片显示异常

### ISSUE THREAD

**Issue by zoffyzhang** [antvis/L7Draw#111]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [L7 Draw](https://codesandbox.io/s/l7draw-issue-template-df75t7) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce

把官方例子 docs/example/point/image.tsx 中的图片链接替换为其他图片，如 https://gw.alipayobjects.com/zos/antfincdn/tWx6gaMr9P/zhongguoyinhang.png
绘制出来的点显示异常

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/11470090/206346649-30e271c1-21a8-4465-8a83-06f8c5b02412.png">

### 🚑 Any additional [like screenshots]

- **L7Draw Version**:
- **Platform**:

**Comment by heiyexing** [comment]
因为这个示例中对 PNG 图片的颜色进行了覆盖，如果使用你提供的图片进行绘制的话，得通过 callback 把 color 配置关掉
```js
      const drawer = new DrawPoint(scene, {
        style: {
          point: {
            normal: { shape: 'dingwei', size: 10, color: undefined },
            hover: { shape: 'dingwei', size: 20, color: undefined },
            active: { shape: 'dingwei', size: 20 },
            callback: ([layer]: ILayer[]) => {
              layer.color(undefined);
            },
          },
        },
      });
```
