### ISSUE TITLE
🥰 [FEATURE] 关于吸附功能对GeoJSON数据多段线格式的支持

### ISSUE THREAD

**Issue by leechenze** [antvis/L7Draw#120]
在地图中配置的 adsorbOptions.data  只支持单一的GeoJSON数据格式的问题, 希望能对GeoJSON 能支持的所有格式都兼容. 毕竟在业务中应用场景很常见, 并且我的面,线,点,是应该能够支持相互都可以吸附的, 而目前咱们仅支持的单一点,线,面的GeoJSON格式属于功能缺失,且不同类型之间还不可以吸附, 期待更新, 变大变强!!!~~~

**Comment by leechenze** [comment]
关于吸附功能对GeoJSON数据多段线格式的支持

**Comment by heiyexing** [comment]
https://github.com/antvis/L7Draw/pull/144
