### ISSUE TITLE
🐛 [BUG] multiple:false 在设置 initialData 后表现错误

### ISSUE THREAD

**Issue by BraisedChicken** [antvis/L7Draw#131]
### 🐛 Bug description [Please make everyone to understand it]
初始化DrawPolygon类时，设置 `multiple:false` 和 `initialData`，此时，地图展示initialData对应的图形，同时仍然可以进行新多边形的绘制，此时进行绘制，会继续增加一个多边形，然后无法新创建多边形。

> Please provide a link by forking these links [L7 Draw](https://codesandbox.io/s/l7draw-issue-template-df75t7) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

 https://codesandbox.io/embed/upbeat-tharp-5dzmml?fontsize=14&hidenavigation=1&theme=dark&view=preview

### 📷 Step to reproduce
参考codesandbox，只要设置 `multiple:false` 和 `initialData`即可重现

### 🏞 Expected result
当设置 `multiple:false` 和 `initialData`时，默认应该只允许编辑已有图形。

### 🚑 Any additional [like screenshots]

- **L7Draw Version**: 3.0.25
- **Platform**: Mac

**Comment by heiyexing** [comment]
这块是我的文档表述有误，multiple 指的是每次 enable 时，是否支持绘制多个，如果你需要控制整个 Draw 实例的绘制元素个数上限，可以在 options  里用 maxSize: number 试试
