### ISSUE TITLE
如何禁用绘制面时鼠标按住的拖拽

### ISSUE THREAD

**Issue by spadek-w** [antvis/L7Draw#132]
如何禁用绘制面时鼠标按住的拖拽？
当设置editable: false, // 禁用编辑时 确实可以禁用拖拽，但我想保留快捷操作（回退，重做，删除）。
  scene.on('loaded', () => {
      const drawer = new DrawPolygon(scene, {
        distanceOptions: {},
        areaOptions: {},
        liveUpdate: true,
      });
      drawer.enable();
    });

**Comment by heiyexing** [comment]
禁止拖拽整个 polygon 还是 单个节点？
