### ISSUE TITLE
🤔 [QUESTION]有没有办法只修改单条线的颜色？

### ISSUE THREAD

**Issue by oyal** [antvis/L7Draw#141]
修改图层颜色layer.color会把所有的线的颜色改变，有没有办法只修改特定线的颜色？🤔

**Comment by heiyexing** [comment]
具体是在什么场景下会需要去改单条线的颜色？我这边需要评估一下这个需求通不通用。

**Comment by oyal** [comment]
> 具体是在什么场景下会需要去改单条线的颜色？我这边需要评估一下这个需求通不通用。

目前在画一个天然气管道分布图，有一些业务数据放在了properties中，比如我想根据这个value（压力/流量）范围来显示不同的颜色。L7Draw画出来的线好像都是是在一个layer中，我设置layer颜色会把所有的颜色改变

![image](https://github.com/antvis/L7Draw/assets/88022434/29adebb1-a81b-4915-8e5e-a0097fd0f915)

**Comment by heiyexing** [comment]
可以使用 style 中的  callback 获取到底层的 layer 实例，自定义 properties 与颜色的值映射关系

![image](https://github.com/antvis/L7Draw/assets/29321750/535c89f8-bf7c-4d6a-a16f-91a229db2330)

**Comment by heiyexing** [comment]
现在的 layer 默认是按照

**Comment by heiyexing** [comment]
我建议你在绘制的时候还是按照 L7Draw 一种颜色的展示方案来绘制  绘制结束之后，你可以清空 Draw 中的数据，然后用自定义的图层和拆解出来的 LineString Feature 去呈现
