### ISSUE TITLE
🥰 [FEATURE] 希望官方可以给出vue的demo示例

### ISSUE THREAD

**Issue by wangenze267** [antvis/L7Draw#142]
### 🚑 Any additional [like screenshots]
希望官方可以给出vue的demo示例

**Comment by heiyexing** [comment]
L7Draw 跟 L7 一样是和 MVVM 框架解耦的库，所以不会提供 Vue 或者 React 环境下的使用姿势的，都是在正常生命周期钩子里 new 出来就行了。
