### ISSUE TITLE
增加一个可绘制的 marker 

### ISSUE THREAD

**Issue by dozedoze** [antvis/L7Draw#156]
### 💻 Features description
增加一个可绘制的  l7中的 marker 标注（可自定义点内容）

### 🏞 What problem does this feature solve
针对自定义点内容较强的场景

### 🧐 What does the proposed API look like
类似 l7 中的marker  增加一个element 属性
initData 中的 Geojson 感觉可以在类型 point 上做一些 properties 的扩展来识别是marker

**Comment by dozedoze** [comment]
> marker 和 Layer 的渲染机制是不一样的，如果在 `PointLayer` 支持编辑 Marker 成本较大，你的使用场景具体是怎么样的
我遇到的具体场景是： 在某一条路线上点击可以渲染一个 l7 默认样式Marker （可以多次点击，并渲染多个marker）， 且这里所有的marker都是可以被拖拽的。
功能跟绘制点无线类似， 就差这个点样式了

**Comment by dozedoze** [comment]
> marker 和 Layer 的渲染机制是不一样的，如果在 `PointLayer` 支持编辑 Marker 成本较大，你的使用场景具体是怎么样的

我遇到的具体场景是： 在某一条路线上点击可以渲染一个 l7 默认样式Marker （可以多次点击，并渲染多个marker）， 且这里所有的marker都是可以被拖拽的。
功能跟绘制点无限类似， 就差这个点样式了

**Comment by heiyexing** [comment]
L7 层面的 Marker 已支持拖拽能力，可以等下一个版本发布 https://github.com/antvis/L7/pull/2274
