### ISSUE TITLE
🐛 [BUG]使用L7集成L7Draw，发现无效图层的bug

### ISSUE THREAD

**Issue by xiaonanfeng** [antvis/L7Draw#157]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [L7 Draw](https://codesandbox.io/s/l7draw-issue-template-df75t7) or GitHub repo, a minimal reproduction.

drawControl() {
    const drawControl = new DrawControl(this.scene, {
      position: 'topright',
      drawConfig: {
        point: {
          autoActive: false,
          editable: false
        },
        line: {
          autoActive: false,
          editable: false
        },
        polygon: {
          autoActive: false,
          editable: false
        },
        rect: {
          autoActive: false,
          editable: false
        },
        circle: {
          autoActive: false,
          editable: false
        },
        clear: {
          autoActive: false,
          editable: false
        },
      }
    });
    // drawControl.on(ControlEvent.DrawChange, (changeType) => {
    //   console.log(changeType);
    // });
    // drawControl.on(ControlEvent.DataChange, (val) => {
    //   console.log(val);
    // })
    // drawControl.on(ControlEvent.DrawSelect, (val) => {
    //   console.log(val);
    // });
    // drawControl.on(ControlEvent.DrawClear, (val) => {
    //   console.log(val);
    // })
    return drawControl;
  }

- _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce
使用L7作为地图的前端显示引擎，在使用scene.getLayers()方的时候，发现有20多个无效图层。
### 🏞 Expected result
如何关闭L7Draw的无效图层，或者能精准的过滤掉无效图层。
### 🚑 Any additional [like screenshots]
![image](https://github.com/antvis/L7Draw/assets/29450279/9732505c-84e4-49b9-bd68-da83f7e902cd)
- **L7Draw Version**:
- **Platform**:

**Comment by 947840309** [comment]
你只获取你需要的涂层不就可以了

**Comment by heiyexing** [comment]
L7Draw 底层就是通过图层来达成绘制效果的，这边建议你给你要获取的图层一个 id 或 name，在通过 scene.getLayer 去获取
