### ISSUE TITLE
🐛 [BUG]utils/common里面的getLngLat 方法获取经纬度属性访问问题

### ISSUE THREAD

**Issue by siluozhang516** [antvis/L7Draw#174]
/**
 * 磨平L7 Scene 鼠标事件返回的经纬度差异
 * @param e
 */
export const getLngLat = (e: ISceneMouseEvent | ILayerMouseEvent) => {
  // @ts-ignore
  return e.lngLat || e.lnglat;
};

可修改成   return e.lngLat || e.lnglat || e.latlng; 在leaflet中不会报错

**Comment by heiyexing** [comment]
https://github.com/antvis/L7Draw/pull/176
