### ISSUE TITLE
DrawCircle 和 DrawRect 提供指定初始数据的功能

### ISSUE THREAD

**Issue by seymoe** [antvis/L7Draw#30]
文档中提到：

## 配置项 DrawOption
+ data `geojson' 初始化数据仅支持 Polygon, Line, Point, 不支持MultPolygon,Circle 可用编辑现有数据

请问能否支持 Circle 和 Rect 指定初始数据？

或者有什么其他方法能够实现保存的绘制数据能够回显出来？

**Comment by lzxue** [comment]
rect 已经添加了
