### ISSUE TITLE
绘制的面是如何放在其他图层上的

### ISSUE THREAD

**Issue by zhanghjtx** [antvis/L7Draw#85]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [L7 Draw](https://codesandbox.io/s/l7draw-issue-template-df75t7) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

- **L7Draw Version**:
- **Platform**:

**Comment by heiyexing** [comment]
不是特别理解您想表达的意思
