### ISSUE TITLE
如何支持简单坐标系（非地理坐标系）

### ISSUE THREAD

**Issue by fatesq** [antvis/L7Draw#92]
https://l7.antv.vision/zh/docs/api/experiment/simpleCoordinates/#gatsby-focus-wrapper
如何在平面图上绘制点和面

**Comment by heiyexing** [comment]
L7 Draw 目前主要还是定位于基于 **经纬度** 坐标进行绘制，暂不支持简单坐标系的 **x/y** 坐标系，可以尝试使用其他的2D图形绘制库来满足您的需求，如 Fabric.js

**Comment by BigKongfuPanda** [comment]
> L7 Draw 目前主要还是定位于基于 **经纬度** 坐标进行绘制，暂不支持简单坐标系的 **x/y** 坐标系，可以尝试使用其他的2D图形绘制库来满足您的需求，如 Fabric.js

请问现在支持了吗？我发现在简单坐标系中绘制点，获取的坐标值是经纬度，而不是X/Y
